### PR TITLE
add learnings from issue #1000

### PR DESCRIPTION
**Pull request by mi-hol**

### CODE REVIEW

**Comment by mi-hol** [comment]
Signed-off-by: mi-hol 22799428+mi-hol@users.noreply.github.com

**Comment by votdev** [comment]
Could you please add some notes what this PR is about? Is it by intention to reorder the questions? This makes it harder to review this PR.

**Review by votdev — CHANGES_REQUESTED** [review]
Could you please add some notes what this PR is about? Is it by intention to reorder the questions? This makes it harder to review this PR.

**Comment by mi-hol** [comment]
> Could you please add some notes what this PR is about? Is it by intention to reorder the questions? This makes it harder to review this PR.

yes, first are all issues related to webui grouped together.
last, added instruction to troubleshoot plug-in issues from issue #1000

**Comment by mi-hol** [comment]
Thanks for merging into branch 5.x already, I thought I'd have to request this as a second task. 
Will this be the new standard procedure?

**Comment by votdev** [comment]
> Thanks for merging into branch 5.x already, I thought I'd have to request this as a second task.
> Will this be the new standard procedure?

No, but i'm working on the docs right at the moment, so it was problem for me to do this.

**Pull request merged**
