### PR TITLE
Update index.rst

### PR DESCRIPTION
**Pull request by mi-hol**
Fixes: https://github.com/openmediavault/openmediavault-docs/issues/87

Signed-off-by: mi-hol 22799428+mi-hol@users.noreply.github.com

### CODE REVIEW

**Comment by votdev** [comment]
Superseded by 64086d90f76a40f49c421328907f8d83e467fa73 which removes duplicate information from the index page. The information is already mentioned in the installation variants sub-pages.

**Comment by mi-hol** [comment]
> Superseded by [64086d9](https://github.com/openmediavault/openmediavault-docs/commit/64086d90f76a40f49c421328907f8d83e467fa73) which removes duplicate information from the index page

Unfortunately an important aspect regarding the different approaches required for x86/amd64 and arm32/arm64 that I tried to add via my PR is not yet covered by 64086d9. 

From my view this missing distinction is the reason for the many non-official instructions to install OMV on SBC.s As I learned the hard way 2 years ago, these instructions are not reflecting important changes happening in OMV and lead to errors. Many of these errors end up as forum posts or frustrated users spreading bad news about OMV by word of mouth or generic forums.

How could we address this issue?

**Comment by ryecoaaron** [comment]
What is missing? The install script isn’t just for arm devices and you can using the debian iso/install script for advanced installs.

**Comment by votdev** [comment]
> > Superseded by [64086d9](https://github.com/openmediavault/openmediavault-docs/commit/64086d90f76a40f49c421328907f8d83e467fa73) which removes duplicate information from the index page
> 
> Unfortunately an important aspect regarding the different approaches required for x86/amd64 and arm32/arm64 that I tried to add via my PR is not yet covered by [64086d9](https://github.com/openmediavault/openmediavault-docs/commit/64086d90f76a40f49c421328907f8d83e467fa73).
> 
> From my view this missing distinction is the reason for the many non-official instructions to install OMV on SBC.s As I learned the hard way 2 years ago, these instructions are not reflecting important changes happening in OMV and lead to errors. Many of these errors end up as forum posts or frustrated users spreading bad news about OMV by word of mouth or generic forums.
> 
> How could we address this issue?

IMO you only rearranged the order of the already available information on this page. I removed them because:
- Disconnecting disks only applies to ISO installations. This is already covered in [Installation using an ISO image](https://docs.openmediavault.org/en/stable/installation/via_iso.html). It's not necessary to duplicate information (which is also incorrect for other install variants than ISO).
- The Link to the omv-extras.org install script is already mentioned in [Installation on Debian](https://docs.openmediavault.org/en/stable/installation/on_debian.html).

Perhaps the explanation of which installation variant should be used in which scenario could be improved. 

If you've tried to improve that with your PR, feel free to submit another PR that highlights that more accurately. I can also re-open this PR if you want to refactor it.

**Comment by votdev** [comment]
I've added a note about which installation variant to use and when with https://github.com/openmediavault/openmediavault-docs/commit/f8b5fe75845827c4b5dfe6af0d85b36af0bce8f0. So the issue should be fixed now, right?

**Comment by mi-hol** [comment]
> I've added a note about which installation variant to use and when with [f8b5fe7](https://github.com/openmediavault/openmediavault-docs/commit/f8b5fe75845827c4b5dfe6af0d85b36af0bce8f0). So the issue should be fixed now, right?

Thanks Volker, this change fixed the issue.

**Pull request closed without merging**
