### PR TITLE
Update on_debian.rst

### PR DESCRIPTION
**Pull request by matiprogram**
It doesnt work with the Debian 11, a note

### CODE REVIEW

**Comment by ryecoaaron** [comment]
OMV 6.x installs just fine on Debian 11.  OMV 5.x installs on Debian 10.  What isn't working with Debian 11?

**Comment by matiprogram** [comment]
There's a problem with an PHP dependency (phapi-20180731) and apt gives an error (error e: unable to correct problems, you have held broken packages) , tried with multiple computers and nothing, in debian 10 works just fine

**Comment by ryecoaaron** [comment]
OMV 5.x MUST use Debian 10.
OMV 6.x MUST use Debian 11.
Your php error tells me you are trying to install OMV 5 on Debian 11.  That will not work.  I recommend using the install script to install OMV - https://github.com/OpenMediaVault-Plugin-Developers/installScript - since it will do the right thing here.

**Comment by votdev** [comment]
I'm closing this issue because [phpapi-20180731](https://packages.debian.org/buster/phpapi-20180731) is a virtual package in Debian 10 (Buster). Another reason is this PR is opened against the wrong branch.

**Pull request closed without merging**
