### PR TITLE
Create NewUserGuide.rst

### PR DESCRIPTION
**Pull request by flmaxey**
Testing a doc merge.

### CODE REVIEW

**Comment by flmaxey** [comment]
test merge

**Review by flmaxey — COMMENTED** [review]
Test merge

**Review by mi-hol — APPROVED** [review]
ok ;-)

**Review by mi-hol — APPROVED** [review]
looks good

**Comment by mi-hol** [comment]
@voldev,  weird my review & approval doesn't trigger the status change from "Review required" to allow merging.
Maybe a permission issue?

**Review by votdev — APPROVED** [review]

**Comment by votdev** [comment]
> @voldev, weird my review & approval doesn't trigger the status change from "Review required" to allow merging.
> Maybe a permission issue?

I've no idea why this happens and i've not found anything in the settings that may be related to this. IMO all should work correct.

**Comment by flmaxey** [comment]
This commit won't merge without signing.  I didn't have a GPG cert attach to my github user ID. when the PR was created, and it appears that I can't retroactively sign this commit.

Closing the PR.

**Pull request closed without merging**
